version: "1"
rules:
  - base: main
    upstream: carpentries:main
    mergeMethod: hardreset
    mergeUnstable: false
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
