name: "Receive Pull Request"

on:
  pull_request:
    types:
      [opened, synchronize, reopened]

jobs:
  build-md-source:
    name: "Build Markdown Source Files"
    runs-on: macOS-latest
    if: ${{ github.event.action != 'closed' }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/Library/Application Support/renv
      CHIVE: ${{ github.workspace }}/site/chive
      PR: ${{ github.workspace }}/site/pr
      MD: ${{ github.workspace }}/site/built
    steps:
      - name: "Check Out Main Branch"
        uses: actions/checkout@v2

      - name: "Check Out Staging Branch"
        uses: actions/checkout@v2
        with:
          ref: md-outputs
          path: ${{ env.MD }}

      - name: "Set up R"
        uses: r-lib/actions/setup-r@v1

      - name: "Set up Pandoc"
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: "2.11.4"

      - name: "Query Sandpaper Dependencies"
        run: |
          install.packages('remotes')
          options(repos = c(
            "https://carpentries.r-universe.dev/", 
            "https://carpentries.github.io/drat/",
            "https://cloud.r-project.org/"
          ))
          saveRDS(remotes::package_deps('sandpaper', dependencies = TRUE), 
            ".github/depends.Rds", 
            version = 2
          )
          writeLines(
            sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), 
            ".github/R-version"
          )
        shell: Rscript {0}

      - name: "Restore Package Cache"
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: "Restore {renv} Cache"
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys:
            ${{ runner.os }}-renv-

      - name: "Install {sandpaper} and Dependencies"
        run: |
          options(repos = c(
            "https://carpentries.r-universe.dev/", 
            "https://carpentries.github.io/drat/",
            "https://cloud.r-project.org/"
          ))
          library("remotes")
          pkgs <- package_deps('sandpaper', dependencies = TRUE)
          pkgs$diff[pkgs$package == "tinkr"] <- -1 # force tinkr update for now
          update(pkgs, upgrade = "always")
          # update to use renv version of sandpaper
          if (!"renv_carpentries_repos" %in% ls(env = asNamespace("sandpaper")))
            install_github("carpentries/sandpaper@package-management")
        shell: Rscript {0}

      - name: "Fortify Local {renv} Packages"
        run: sandpaper::manage_deps(path = '${{ github.workspace }}', quiet = FALSE)
        shell: Rscript {0}

      - name: "Show Session Information"
        run: sandpaper:::ci_session_info()
        shell: Rscript {0}

      - name: "Build Site"
        id: build-site
        run: sandpaper:::build_markdown(path = '${{ github.workspace }}', quiet = TRUE)
        shell: Rscript {0}

      - name: "Generate Artifacts"
        id: generate-artifacts
        run: |
          sandpaper:::ci_bundle_pr_artifacts(
            repo         = '${{ github.repository }}',
            pr_number    = '${{ github.event.number }}',
            path_md      = '${{ env.MD }}',
            path_pr      = '${{ env.PR }}',
            path_archive = '${{ env.CHIVE }}',
            branch       = 'md-outputs'
          )
        shell: Rscript {0}

      - name: "Upload PR"
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ${{ env.PR }}

      - name: "Upload Diff"
        uses: actions/upload-artifact@v2
        with:
          name: diff
          path: ${{ env.CHIVE }}
          retention-days: 1
      
      - name: "Upload Build"
        uses: actions/upload-artifact@v2
        with:
          name: built
          path: ${{ env.MD }}
          retention-days: 1

      - name: "Teardown"
        run: sandpaper::reset_site()
        shell: Rscript {0}
