name: "02 Maintain: Update Workflow Files"

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who triggered this build (enter github username to tag yourself)?'
        required: true
        default: 'weekly run'
      tarball:
        description: 'Absolute URL to the desired sandpaper repo tarball'
        required: false
      clean:
        description: 'Workflow files/file extensions to clean (no wildcards, enter "" for none)'
        required: false
        default: '.yaml'
  schedule:
    # Run every Tuesday
    - cron: '0 0 * * 2'

jobs:
  update_workflow:
    name: "Update Workflow"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: Update Workflows
        id: update
        uses: froggleston/actions/update-workflows@main
        with:
          repo: ${{ github.event.inputs.tarball }}
          clean: ${{ github.event.inputs.clean }}

      - name: Create Pull Request
        id: cpr
        if: "${{ steps.update.outputs.new }}"
        uses: carpentries/create-pull-request@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          branch: "update/workflows"
          commit-message: "[actions] update sandpaper workflow to version ${{ steps.update.outputs.new }}"
          title: "Update Workflows to Version ${{ steps.update.outputs.new }}"
          body: |
            :robot: This is an automated build

            Update Workflows from sandpaper version ${{ steps.update.outputs.old }} -> ${{ steps.update.outputs.new }}

            - Auto-generated by [create-pull-request][1] on ${{ steps.update.outputs.date }}

            [1]: https://github.com/carpentries/create-pull-request/tree/main
          labels: "type: template and tools"
          draft: false
