name: "04 Maintain: Update Workflow Files"

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who triggered this build (enter github username to tag yourself)?'
        required: true
        default: 'weekly run'
      tarball:
        description: 'Absolute URL to the desired sandpaper repo tarball'
        required: false
        default: ''
      clean:
        description: 'Workflow files/file extensions to clean (no wildcards, enter "" for none)'
        required: false
        default: '.yaml'

jobs:
  update_workflow:
    name: "Update Workflow"
    runs-on: ubuntu-latest
    needs: check_token
    permissions:
      contents: write
      pull-requests: write
      id-token: write # OIDC permission required
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Validate Current Org and Workflow"
        id: validate-org-workflow
        uses: froggleston/actions/validate-org-workflow@main
        with:
          repo: ${{ github.repository }}
          workflow: ${{ github.workflow }}
        secrets:
          aws_gh_oidc_arn: ${{ secrets.AWS_GH_OIDC_ARN }}
          aws_gh_oidc_region: ${{ secrets.AWS_GH_OIDC_REGION }}

      - name: Set PAT from AWS Secrets Manager
        if: ${{ steps.validate-org-workflow.outputs.is_valid == 'true' }}
        id: set-pat
        shell: bash
        run: |
          SECRET=$(aws secretsmanager get-secret-value \
                   --secret-id carpentries-bot/github-pat \
                   --query SecretString --output text)
          PAT=$(echo "$SECRET" | jq -r .[])
          echo "::add-mask::$PAT"
          echo "pat=$PAT" >> "$GITHUB_OUTPUT"

      - name: "Validate token"
        id: validate-token
        uses: carpentries/actions/check-valid-credentials@main
        with:
          token: ${{ secrets.SANDPAPER_WORKFLOW || steps.set-pat.outputs.pat }}

      - name: Update Workflows
        id: update
        if: ${{ steps.validate-token.outputs.wf == 'true' }}
        uses: carpentries/actions/update-workflows@main
        with:
          repo: ${{ github.event.inputs.tarball }} || "https://carpentries.r-universe.dev"
          clean: ${{ github.event.inputs.clean }} || ".yaml"

      - name: Create Pull Request
        id: cpr
        if: ${{ steps.update.outputs.new > 0 && steps.validate-token.outputs.wf == 'true' }}
        uses: carpentries/create-pull-request@main
        with:
          token: ${{ secrets.SANDPAPER_WORKFLOW || steps.set-pat.outputs.pat }}
          delete-branch: true
          branch: "update/workflows"
          commit-message: "[actions] update sandpaper workflow to version ${{ steps.update.outputs.new }}"
          title: "Update Workflows to Version ${{ steps.update.outputs.new }}"
          body: |
            :robot: This is an automated build

            Update Workflows from sandpaper version ${{ steps.update.outputs.old }} -> ${{ steps.update.outputs.new }}

            - Auto-generated by [create-pull-request][1] on ${{ steps.update.outputs.date }}

            [1]: https://github.com/carpentries/create-pull-request/tree/main
          labels: "type: template and tools"
          draft: false
